stages:
  - build
  - test
  - deploy

deployDocker:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" -t $CI_REGISTRY_IMAGE:latest .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE:latest"
    - docker rmi "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  after_script:
    - docker logout

deployK8s:
  stage: deploy
  script:
    - microk8s kubectl apply -f ./k8s/ec-fr-customer-deployment.yaml
    - microk8s kubectl apply -f ./k8s/ec-fr-customer-service.yaml
    - microk8s kubectl rollout restart deployment ec-fr-customer -n customer-frontend
  needs: ["deployDocker"]
