stages:
  - build
  - test
  - deploy

variables:
  PROJECT: ci-ec-fr-customer


reactDeploy:
  stage: deploy
  script:
    - docker container stop $(docker container ls --filter ancestor=$PROJECT -aq) || true
    - docker container prune --filter ancestor=$PROJECT -f
    - docker build -t $PROJECT:latest .
    - docker run -d -l label=$PROJECT -p 80:80 $PROJECT:latest
