apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-fr-customer
  labels:
    app: ec-fr-customer
spec:
  selector:
    matchLabels:
      app: ec-fr-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: ec-fr-customer
    spec:
      containers:
      - name: ec-fr-customer
        image: joeyfontys/ec-fr-customer
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 64m
            memory: 100Mi
          limits:
            cpu: 400m
            memory: 400Mi

