apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: customer-frontend
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-fr-customer
  namespace: customer-frontend
spec:
  selector:
    matchLabels:
      app: ec-fr-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: ec-fr-customer
    spec:
      containers:
      - name: ec-fr-customer
        image: joeyfontys/ec-fr-customer
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      restartPolicy: Always
