apiVersion: v1
kind: Namespace
metadata:
  name: customer-frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-fr-customer
  namespace: customer-frontend
spec:
  selector:
    matchLabels:
      app: ec-fr-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: ec-fr-customer
    spec:
      hostNetwork: true
      containers:
      - name: ec-fr-customer
        image: joeyfontys/ec-fr-customer
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 1
