apiVersion: v1
kind: Service
metadata:
  name: ec-fr-customer
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: ec-fr-customer
