apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec-fr-customer
spec:
  selector:
    matchLabels:
      app: ec-fr-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: ec-fr-customer
    spec:
      containers:
      - name: ec-fr-customer
        image: joeyfontys/ec-fr-customer
        ports:
        - containerPort: 80
        env:
          - name: API_HOST
            value: ec-auth-deployment
          - name: API_HOT
            value: "test"
      restartPolicy: Always
